# Generated by Django 5.2 on 2025-04-23 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate_mean', models.FloatField(default=75.0)),
                ('heart_rate_variance', models.FloatField(default=5.0)),
                ('systolic_mean', models.FloatField(default=120.0)),
                ('systolic_variance', models.FloatField(default=10.0)),
                ('diastolic_mean', models.FloatField(default=80.0)),
                ('diastolic_variance', models.FloatField(default=5.0)),
                ('pulse_mean', models.IntegerField(default=72)),
                ('pulse_variance', models.PositiveSmallIntegerField(default=1)),
                ('spo2_mean', models.FloatField(default=97.0)),
                ('spo2_variance', models.FloatField(default=1.0)),
                ('steps_mean', models.IntegerField(default=8000)),
                ('steps_variance', models.IntegerField(default=2000)),
                ('distance_mean', models.FloatField(default=0.1)),
                ('sleep_mean', models.FloatField(default=7.5)),
                ('sleep_variance', models.FloatField(default=1.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
