# Generated by Django 5.2 on 2025-04-18 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('device', 'Device'), ('simulated', 'Simulated')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('systolic', models.PositiveSmallIntegerField()),
                ('diastolic', models.PositiveSmallIntegerField()),
                ('pulse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'timestamp'], name='health_metr_user_id_66b641_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailySteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('device', 'Device'), ('simulated', 'Simulated')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField()),
                ('goal', models.PositiveIntegerField(default=10000)),
                ('device', models.CharField(choices=[('PHONE', 'Smartphone'), ('WATCH', 'Smart Watch'), ('PEDOMETER', 'Dedicated Pedometer'), ('OTHER', 'Other Device')], default='OTHER', max_length=50)),
                ('distance', models.FloatField(blank=True, help_text='Distance in kilometers', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'timestamp'], name='health_metr_user_id_14d175_idx')],
            },
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('device', 'Device'), ('simulated', 'Simulated')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveSmallIntegerField()),
                ('activity_level', models.CharField(choices=[('resting', 'Resting'), ('active', 'Active'), ('sleeping', 'Sleeping')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'timestamp'], name='health_metr_user_id_9eef61_idx')],
            },
        ),
        migrations.CreateModel(
            name='SleepDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('device', 'Device'), ('simulated', 'Simulated')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('quality', models.PositiveSmallIntegerField(blank=True, help_text='Subjective sleep quality on a scale of 1-10', null=True)),
                ('interruptions', models.PositiveSmallIntegerField(blank=True, help_text='Number of times sleep was interrupted.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'timestamp'], name='health_metr_user_id_2f423e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('device', 'Device'), ('simulated', 'Simulated')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveSmallIntegerField()),
                ('measurement_method', models.CharField(choices=[('FINGERTIP', 'Fingertip Pulse Oximeter'), ('MEDICAL', 'Medical-Grade Device'), ('WEARABLE', 'Wearable Device'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'timestamp'], name='health_metr_user_id_f7aab7_idx')],
            },
        ),
    ]
